export const etapasChoices = [
  { value: 'Bienvenida', label: 'Bienvenida' },
  { value: 'Visita Técnica', label: 'V.T.' },
  { value: 'Diseño e Ingeniería', label: 'Ingeniería' },
  { value: 'Pre Obras', label: 'Pre Obras' },
  { value: 'Obras', label: 'Obras' },
  { value: 'Tramitación TE4', label: 'TE4' },
  { value: 'Tramitación F5', label: 'F5' },
  {
    value: 'Cambio de medidor y Protocolo de Conexión',
    label: 'P.C.',
  },
  { value: 'Proyecto finalizado', label: 'Finalizado' },
] as const;

export type EtapaProyectoType = (typeof etapasChoices)[number]['value'];

export const estadosChoices = [
  {
    value: 'verde',
    label: 'Verde',
    className: 'bg-green-500 focus:bg-green-600 my-[1px] h-8 border border-white',
  },
  {
    value: 'amarillo',
    label: 'Amarillo',
    className: 'bg-yellow-500 focus:bg-yellow-600 my-[1px] h-8 border border-white',
  },
  {
    value: 'rojo',
    label: 'Rojo',
    className: 'bg-red-500 focus:bg-red-600 my-[1px] h-8 border border-white',
  },
] as const;

export type EstadoProyectoType = (typeof estadosChoices)[number]['value'];

export const tipoEmpalmeChoices = [
  { value: 'Monofásico', label: 'Monofásico' },
  { value: 'Trifásico', label: 'Trifásico' },
] as const;

export type EmpalmeType = (typeof tipoEmpalmeChoices)[number]['value'];

export const tipoProyectoChoices = [
  { value: 'OnGrid', label: 'OnGrid' },
  { value: 'OffGrid', label: 'OffGrid' },
  { value: 'Inyección 0', label: 'Inyección 0' },
] as const;

export type ProyectoType = (typeof tipoProyectoChoices)[number]['value'];

export const tipoInstalacionChoices = [
  { value: 'Techo', label: 'Techo' },
  { value: 'Piso', label: 'Piso' },
  { value: 'Carport', label: 'Carport' },
] as const;

export type InstalacionType = (typeof tipoInstalacionChoices)[number]['value'];

export const sistemaRespaldoChoices = [
  { value: 'No', label: 'No' },
  { value: 'BackupBox', label: 'BackupBox' },
  { value: 'SmartGuard', label: 'SmartGuard' },
] as const;

export type SistemaRespaldoType = (typeof sistemaRespaldoChoices)[number]['value'];

export const cargadorElectricoChoices = [
  { value: 'No', label: 'No' },
  { value: 'Tesla', label: 'Tesla' },
  { value: 'Huawei', label: 'Huawei' },
] as const;

export type CargadorElectricoType = (typeof cargadorElectricoChoices)[number]['value'];

export const bancosChoices = [
  { value: 'Banco de Chile', label: 'Banco de Chile' },
  { value: 'Banco Santander', label: 'Banco Santander' },
  { value: 'Banco Estado', label: 'Banco Estado' },
  { value: 'Banco Itau', label: 'Banco Itaú' },
  { value: 'Banco BCI', label: 'Banco BCI' },
  { value: 'Banco Scotiabank', label: 'Banco Scotiabank' },
  { value: 'Banco Security', label: 'Banco Security' },
  { value: 'Banco Falabella', label: 'Banco Falabella' },
  { value: 'Banco Ripley', label: 'Banco Ripley' },
  { value: 'Banco Consorcio', label: 'Banco Consorcio' },
  { value: 'Banco Internacional', label: 'Banco Internacional' },
  { value: 'Banco BICE', label: 'Banco BICE' },
  { value: 'Banco CrediChile', label: 'Banco CrediChile' },
  { value: 'otro', label: 'Otro' },
] as const;

export type BancoType = (typeof bancosChoices)[number]['value'];

export const distribuidorasChoices = [
  { value: 'Enel', label: 'Enel' },
  { value: 'CGE', label: 'CGE' },
  { value: 'Chilquinta', label: 'Chilquinta' },
  { value: 'CEC', label: 'CEC' },
  { value: 'Codiner', label: 'Codiner' },
  { value: 'Coelcha', label: 'Coelcha' },
  { value: 'Colina', label: 'Colina' },
  { value: 'Coopelan', label: 'Coopelan' },
  { value: 'Coopersol', label: 'Coopersol' },
  { value: 'Coooprel', label: 'Coooprel' },
  { value: 'Coprel', label: 'Coprel' },
  { value: 'Crell', label: 'Crell' },
  { value: 'Edecsa', label: 'Edecsa' },
  { value: 'Edelaysen', label: 'Edelaysen' },
  { value: 'Edelmag', label: 'Edelmag' },
  { value: 'Emelca', label: 'Emelca' },
  { value: 'Frontel', label: 'Frontel' },
  { value: 'Litoral', label: 'Litoral' },
  { value: 'Luz Osorno', label: 'Luz Osorno' },
  { value: 'Luz Parral', label: 'Luz Parral' },
  { value: 'Luzandes', label: 'Luzandes' },
  { value: 'Luzlinares', label: 'Luzlinares' },
  { value: 'Puente Alto', label: 'Puente Alto' },
  { value: 'Saesa', label: 'Saesa' },
  { value: 'Socoepa', label: 'Socoepa' },
  { value: 'Til Til', label: 'Til Til' },
] as const;

export type DistribuidoraType = (typeof distribuidorasChoices)[number]['value'];

export const financiamientoChoices = [
  { value: 'Webpay', label: 'Webpay' },
  { value: 'Leasing', label: 'Leasing' },
  { value: 'Directo', label: 'Directo' },
] as const;

export type FinanciamientoType = (typeof financiamientoChoices)[number]['value'];

export const opcionTarifaChoices = [
  { value: 'BT1', label: 'BT1' },
  { value: 'BT2', label: 'BT2' },
  { value: 'BT3', label: 'BT3' },
  { value: 'BT4', label: 'BT4' },
  { value: 'BT4.1', label: 'BT4.1' },
  { value: 'BT4.2', label: 'BT4.2' },
  { value: 'BT4.3', label: 'BT4.3' },
  { value: 'BT4.4', label: 'BT4.4' },
  { value: 'AT1', label: 'AT1' },
  { value: 'AT2', label: 'AT2' },
  { value: 'AT3', label: 'AT3' },
  { value: 'AT4', label: 'AT4' },
  { value: 'AT4.1', label: 'AT4.1' },
  { value: 'AT4.2', label: 'AT4.2' },
  { value: 'AT4.3', label: 'AT4.3' },
] as const;

export type TarifaType = (typeof opcionTarifaChoices)[number]['value'];

export const facturacionChoices = [
  { value: 'Persona Natural', label: 'Persona Natural' },
  { value: 'Persona Jurídica', label: 'Persona Jurídica' },
] as const;

export type FacturacionType = (typeof facturacionChoices)[number]['value'];

export const estadoDePagoChoices = [
  { value: 'Ok por el momento', label: 'Ok por el momento' },
  { value: 'Facturar pronto', label: 'Facturar pronto' },
  { value: 'Pagado por Facturar', label: 'Pagado por Facturar' },
  { value: 'Facturado por Pagar', label: 'Facturado por Pagar' },
  { value: 'Facturado y Pagado', label: 'Facturado y Pagado' },
] as const;

export type EstadoPagoType = (typeof estadoDePagoChoices)[number]['value'];

export const pagoContratistaChoices = [
  { value: 'Avance', label: 'Avance' },
  { value: 'Término de Obras', label: 'Término de Obras' },
  { value: 'Aprobación TE4', label: 'Aprobación TE4' },
] as const;

export type PagoContratistaType = (typeof pagoContratistaChoices)[number]['value'];

export const areaChoices = [
  { value: 'Comercial', label: 'Comercial' },
  { value: 'Operaciones', label: 'Operaciones' },
  { value: 'Finanzas', label: 'Finanzas' },
  { value: 'Software', label: 'Software' },
  { value: 'Gerencia', label: 'Gerencia' },
] as const;

export type AreaType = (typeof areaChoices)[number]['value'];

export const rolChoices = [
  { value: 'Comercial', label: 'Comercial' },
  { value: 'Operaciones', label: 'Operaciones' },
  { value: 'Admin', label: 'Admin' },
] as const;

export type RolType = (typeof rolChoices)[number]['value'];

export const regionesChoices = [
  {
    value: 'Arica y Parinacota',
    label: 'Arica y Parinacota',
  },
  {
    value: 'Tarapacá',
    label: 'Tarapacá',
  },
  {
    value: 'Antofagasta',
    label: 'Antofagasta',
  },
  {
    value: 'Atacama',
    label: 'Atacama',
  },
  {
    value: 'Coquimbo',
    label: 'Coquimbo',
  },
  {
    value: 'Valparaíso',
    label: 'Valparaíso',
  },
  {
    value: 'Región del Libertador Gral. Bernardo O’Higgins',
    label: 'Región del Libertador Gral. Bernardo O’Higgins',
  },
  {
    value: 'Región del Maule',
    label: 'Región del Maule',
  },
  {
    value: 'Región de Ñuble',
    label: 'Región de Ñuble',
  },
  {
    value: 'Región del Biobío',
    label: 'Región del Biobío',
  },
  {
    value: 'Región de la Araucanía',
    label: 'Región de la Araucanía',
  },
  {
    value: 'Región de Los Ríos',
    label: 'Región de Los Ríos',
  },
  {
    value: 'Región de Los Lagos',
    label: 'Región de Los Lagos',
  },
  {
    value: 'Región Aisén del Gral. Carlos Ibáñez del Campo',
    label: 'Región Aisén del Gral. Carlos Ibáñez del Campo',
  },
  {
    value: 'Región de Magallanes y de la Antártica Chilena',
    label: 'Región de Magallanes y de la Antártica Chilena',
  },
  {
    value: 'Región Metropolitana de Santiago',
    label: 'Región Metropolitana de Santiago',
  },
];

export const comunasChoices = [
  { value: 276, label: 'Aisén' },
  { value: 68, label: 'Algarrobo' },
  { value: 338, label: 'Alhué' },
  { value: 199, label: 'Alto Biobío' },
  { value: 27, label: 'Alto del Carmen' },
  { value: 6, label: 'Alto Hospicio' },
  { value: 254, label: 'Ancud' },
  { value: 32, label: 'Andacollo' },
  { value: 221, label: 'Angol' },
  { value: 289, label: 'Antártica' },
  { value: 12, label: 'Antofagasta' },
  { value: 187, label: 'Antuco' },
  { value: 180, label: 'Arauco' },
  { value: 1, label: 'Arica' },
  { value: 334, label: 'Buin' },
  { value: 153, label: 'Bulnes' },
  { value: 58, label: 'Cabildo' },
  { value: 288, label: 'Cabo de Hornos (Ex Navarino)' },
  { value: 188, label: 'Cabrero' },
  { value: 16, label: 'Calama' },
  { value: 245, label: 'Calbuco' },
  { value: 22, label: 'Caldera' },
  { value: 63, label: 'Calera' },
  { value: 335, label: 'Calera de Tango' },
  { value: 54, label: 'Calle Larga' },
  { value: 2, label: 'Camarones' },
  { value: 8, label: 'Camiña' },
  { value: 37, label: 'Canela' },
  { value: 181, label: 'Cañete' },
  { value: 201, label: 'Carahue' },
  { value: 69, label: 'Cartagena' },
  { value: 46, label: 'Casablanca' },
  { value: 253, label: 'Castro' },
  { value: 74, label: 'Catemu' },
  { value: 126, label: 'Cauquenes' },
  { value: 295, label: 'Cerrillos' },
  { value: 296, label: 'Cerro Navia' },
  { value: 270, label: 'Chaitén' },
  { value: 24, label: 'Chañaral' },
  { value: 127, label: 'Chanco' },
  { value: 107, label: 'Chépica' },
  { value: 169, label: 'Chiguayante' },
  { value: 282, label: 'Chile Chico' },
  { value: 155, label: 'Chillán' },
  { value: 154, label: 'Chillán Viejo' },
  { value: 108, label: 'Chimbarongo' },
  { value: 220, label: 'Cholchol' },
  { value: 255, label: 'Chonchi' },
  { value: 277, label: 'Cisnes' },
  { value: 146, label: 'Cobquecura' },
  { value: 246, label: 'Cochamó' },
  { value: 279, label: 'Cochrane' },
  { value: 84, label: 'Codegua' },
  { value: 147, label: 'Coelemu' },
  { value: 274, label: 'Coihaique' },
  { value: 162, label: 'Coihueco' },
  { value: 85, label: 'Coinco' },
  { value: 139, label: 'Colbún' },
  { value: 9, label: 'Colchane' },
  { value: 330, label: 'Colina' },
  { value: 222, label: 'Collipulli' },
  { value: 86, label: 'Coltauco' },
  { value: 41, label: 'Combarbalá' },
  { value: 167, label: 'Concepción' },
  { value: 297, label: 'Conchalí' },
  { value: 47, label: 'Concón' },
  { value: 117, label: 'Constitución' },
  { value: 182, label: 'Contulmo' },
  { value: 21, label: 'Copiapó' },
  { value: 31, label: 'Coquimbo' },
  { value: 168, label: 'Coronel' },
  { value: 233, label: 'Corral' },
  { value: 202, label: 'Cunco' },
  { value: 223, label: 'Curacautín' },
  { value: 339, label: 'Curacaví' },
  { value: 256, label: 'Curaco de Vélez' },
  { value: 183, label: 'Curanilahue' },
  { value: 203, label: 'Curarrehue' },
  { value: 118, label: 'Curepto' },
  { value: 129, label: 'Curicó' },
  { value: 257, label: 'Dalcahue' },
  { value: 25, label: 'Diego de Almagro' },
  { value: 87, label: 'Doñihue' },
  { value: 298, label: 'El Bosque' },
  { value: 156, label: 'El Carmen' },
  { value: 343, label: 'El Monte' },
  { value: 70, label: 'El Quisco' },
  { value: 71, label: 'El Tabo' },
  { value: 119, label: 'Empedrado' },
  { value: 224, label: 'Ercilla' },
  { value: 299, label: 'Estación Central' },
  { value: 170, label: 'Florida' },
  { value: 204, label: 'Freire' },
  { value: 28, label: 'Freirina' },
  { value: 247, label: 'Fresia' },
  { value: 248, label: 'Frutillar' },
  { value: 271, label: 'Futaleufú' },
  { value: 241, label: 'Futrono' },
  { value: 205, label: 'Galvarino' },
  { value: 4, label: 'General Lagos' },
  { value: 206, label: 'Gorbea' },
  { value: 88, label: 'Graneros' },
  { value: 278, label: 'Guaitecas' },
  { value: 64, label: 'Hijuelas' },
  { value: 272, label: 'Hualaihué' },
  { value: 130, label: 'Hualañé' },
  { value: 178, label: 'Hualpén' },
  { value: 171, label: 'Hualqui' },
  { value: 10, label: 'Huara' },
  { value: 29, label: 'Huasco' },
  { value: 300, label: 'Huechuraba' },
  { value: 36, label: 'Illapel' },
  { value: 301, label: 'Independencia' },
  { value: 5, label: 'Iquique' },
  { value: 344, label: 'Isla de Maipo' },
  { value: 52, label: 'Isla de Pascua' },
  { value: 48, label: 'Juan Fernández' },
  { value: 302, label: 'La Cisterna' },
  { value: 65, label: 'La Cruz' },
  { value: 101, label: 'La Estrella' },
  { value: 303, label: 'La Florida' },
  { value: 242, label: 'Lago Ranco' },
  { value: 275, label: 'Lago Verde' },
  { value: 304, label: 'La Granja' },
  { value: 285, label: 'Laguna Blanca' },
  { value: 33, label: 'La Higuera' },
  { value: 189, label: 'Laja' },
  { value: 57, label: 'La Ligua' },
  { value: 331, label: 'Lampa' },
  { value: 234, label: 'Lanco' },
  { value: 305, label: 'La Pintana' },
  { value: 306, label: 'La Reina' },
  { value: 89, label: 'Las Cabras' },
  { value: 307, label: 'Las Condes' },
  { value: 30, label: 'La Serena' },
  { value: 240, label: 'La Unión' },
  { value: 207, label: 'Lautaro' },
  { value: 179, label: 'Lebu' },
  { value: 131, label: 'Licantén' },
  { value: 80, label: 'Limache' },
  { value: 138, label: 'Linares' },
  { value: 102, label: 'Litueche' },
  { value: 75, label: 'Llaillay' },
  { value: 250, label: 'Llanquihue' },
  { value: 308, label: 'Lo Barnechea' },
  { value: 309, label: 'Lo Espejo' },
  { value: 109, label: 'Lolol' },
  { value: 208, label: 'Loncoche' },
  { value: 140, label: 'Longaví' },
  { value: 225, label: 'Lonquimay' },
  { value: 310, label: 'Lo Prado' },
  { value: 184, label: 'Los Álamos' },
  { value: 53, label: 'Los Andes' },
  { value: 186, label: 'Los Ángeles' },
  { value: 235, label: 'Los Lagos' },
  { value: 249, label: 'Los Muermos' },
  { value: 226, label: 'Los Sauces' },
  { value: 38, label: 'Los Vilos' },
  { value: 172, label: 'Lota' },
  { value: 227, label: 'Lumaco' },
  { value: 90, label: 'Machalí' },
  { value: 311, label: 'Macul' },
  { value: 236, label: 'Máfil' },
  { value: 312, label: 'Maipú' },
  { value: 91, label: 'Malloa' },
  { value: 103, label: 'Marchihue' },
  { value: 20, label: 'María Elena' },
  { value: 340, label: 'María Pinto' },
  { value: 237, label: 'Mariquina' },
  { value: 120, label: 'Maule' },
  { value: 251, label: 'Maullín' },
  { value: 13, label: 'Mejillones' },
  { value: 209, label: 'Melipeuco' },
  { value: 337, label: 'Melipilla' },
  { value: 132, label: 'Molina' },
  { value: 42, label: 'Monte Patria' },
  { value: 92, label: 'Mostazal' },
  { value: 190, label: 'Mulchén' },
  { value: 191, label: 'Nacimiento' },
  { value: 110, label: 'Nancagua' },
  { value: 293, label: 'Natales' },
  { value: 104, label: 'Navidad' },
  { value: 192, label: 'Negrete' },
  { value: 148, label: 'Ninhue' },
  { value: 163, label: 'Ñiquén' },
  { value: 66, label: 'Nogales' },
  { value: 210, label: 'Nueva Imperial' },
  { value: 313, label: 'Ñuñoa' },
  { value: 280, label: 'O’Higgins' },
  { value: 93, label: 'Olivar' },
  { value: 17, label: 'Ollagüe' },
  { value: 81, label: 'Olmué' },
  { value: 263, label: 'Osorno' },
  { value: 40, label: 'Ovalle' },
  { value: 345, label: 'Padre Hurtado' },
  { value: 211, label: 'Padre las Casas' },
  { value: 34, label: 'Paiguano' },
  { value: 238, label: 'Paillaco' },
  { value: 336, label: 'Paine' },
  { value: 273, label: 'Palena' },
  { value: 111, label: 'Palmilla' },
  { value: 239, label: 'Panguipulli' },
  { value: 76, label: 'Panquehue' },
  { value: 59, label: 'Papudo' },
  { value: 105, label: 'Paredones' },
  { value: 141, label: 'Parral' },
  { value: 314, label: 'Pedro Aguirre Cerda' },
  { value: 121, label: 'Pelarco' },
  { value: 128, label: 'Pelluhue' },
  { value: 157, label: 'Pemuco' },
  { value: 346, label: 'Peñaflor' },
  { value: 315, label: 'Peñalolén' },
  { value: 122, label: 'Pencahue' },
  { value: 173, label: 'Penco' },
  { value: 112, label: 'Peralillo' },
  { value: 212, label: 'Perquenco' },
  { value: 60, label: 'Petorca' },
  { value: 94, label: 'Peumo' },
  { value: 11, label: 'Pica' },
  { value: 95, label: 'Pichidegua' },
  { value: 100, label: 'Pichilemu' },
  { value: 158, label: 'Pinto' },
  { value: 328, label: 'Pirque' },
  { value: 213, label: 'Pitrufquén' },
  { value: 113, label: 'Placilla' },
  { value: 149, label: 'Portezuelo' },
  { value: 290, label: 'Porvenir' },
  { value: 7, label: 'Pozo Almonte' },
  { value: 291, label: 'Primavera' },
  { value: 316, label: 'Providencia' },
  { value: 49, label: 'Puchuncaví' },
  { value: 214, label: 'Pucón' },
  { value: 317, label: 'Pudahuel' },
  { value: 327, label: 'Puente Alto' },
  { value: 244, label: 'Puerto Montt' },
  { value: 264, label: 'Puerto Octay' },
  { value: 252, label: 'Puerto Varas' },
  { value: 114, label: 'Pumanque' },
  { value: 43, label: 'Punitaqui' },
  { value: 284, label: 'Punta Arenas' },
  { value: 258, label: 'Puqueldón' },
  { value: 228, label: 'Purén' },
  { value: 265, label: 'Purranque' },
  { value: 77, label: 'Putaendo' },
  { value: 3, label: 'Putre' },
  { value: 266, label: 'Puyehue' },
  { value: 259, label: 'Queilén' },
  { value: 260, label: 'Quellón' },
  { value: 261, label: 'Quemchi' },
  { value: 193, label: 'Quilaco' },
  { value: 318, label: 'Quilicura' },
  { value: 194, label: 'Quilleco' },
  { value: 159, label: 'Quillón' },
  { value: 62, label: 'Quillota' },
  { value: 79, label: 'Quilpué' },
  { value: 262, label: 'Quinchao' },
  { value: 96, label: 'Quinta de Tilcoco' },
  { value: 319, label: 'Quinta Normal' },
  { value: 50, label: 'Quintero' },
  { value: 150, label: 'Quirihue' },
  { value: 83, label: 'Rancagua' },
  { value: 151, label: 'Ránquil' },
  { value: 133, label: 'Rauco' },
  { value: 320, label: 'Recoleta' },
  { value: 229, label: 'Renaico' },
  { value: 321, label: 'Renca' },
  { value: 97, label: 'Rengo' },
  { value: 98, label: 'Requínoa' },
  { value: 142, label: 'Retiro' },
  { value: 55, label: 'Rinconada' },
  { value: 243, label: 'Río Bueno' },
  { value: 123, label: 'Río Claro' },
  { value: 44, label: 'Río Hurtado' },
  { value: 283, label: 'Río Ibáñez' },
  { value: 267, label: 'Río Negro' },
  { value: 286, label: 'Río Verde' },
  { value: 134, label: 'Romeral' },
  { value: 215, label: 'Saavedra' },
  { value: 135, label: 'Sagrada Familia' },
  { value: 39, label: 'Salamanca' },
  { value: 67, label: 'San Antonio' },
  { value: 333, label: 'San Bernardo' },
  { value: 164, label: 'San Carlos' },
  { value: 124, label: 'San Clemente' },
  { value: 56, label: 'San Esteban' },
  { value: 165, label: 'San Fabián' },
  { value: 73, label: 'San Felipe' },
  { value: 106, label: 'San Fernando' },
  { value: 287, label: 'San Gregorio' },
  { value: 160, label: 'San Ignacio' },
  { value: 143, label: 'San Javier' },
  { value: 323, label: 'San Joaquín' },
  { value: 329, label: 'San José de Maipo' },
  { value: 268, label: 'San Juan de la Costa' },
  { value: 324, label: 'San Miguel' },
  { value: 166, label: 'San Nicolás' },
  { value: 269, label: 'San Pablo' },
  { value: 341, label: 'San Pedro' },
  { value: 18, label: 'San Pedro de Atacama' },
  { value: 174, label: 'San Pedro de la Paz' },
  { value: 125, label: 'San Rafael' },
  { value: 325, label: 'San Ramón' },
  { value: 195, label: 'San Rosendo' },
  { value: 196, label: 'Santa Bárbara' },
  { value: 115, label: 'Santa Cruz' },
  { value: 175, label: 'Santa Juana' },
  { value: 78, label: 'Santa María' },
  { value: 322, label: 'Santiago' },
  { value: 72, label: 'Santo Domingo' },
  { value: 99, label: 'San Vicente' },
  { value: 14, label: 'Sierra Gorda' },
  { value: 342, label: 'Talagante' },
  { value: 116, label: 'Talca' },
  { value: 176, label: 'Talcahuano' },
  { value: 15, label: 'Taltal' },
  { value: 200, label: 'Temuco' },
  { value: 136, label: 'Teno' },
  { value: 216, label: 'Teodoro Schmidt' },
  { value: 23, label: 'Tierra Amarilla' },
  { value: 332, label: 'Tiltil' },
  { value: 292, label: 'Timaukel' },
  { value: 185, label: 'Tirúa' },
  { value: 19, label: 'Tocopilla' },
  { value: 217, label: 'Toltén' },
  { value: 177, label: 'Tomé' },
  { value: 294, label: 'Torres del Paine' },
  { value: 281, label: 'Tortel' },
  { value: 230, label: 'Traiguén' },
  { value: 152, label: 'Treguaco' },
  { value: 197, label: 'Tucapel' },
  { value: 232, label: 'Valdivia' },
  { value: 26, label: 'Vallenar' },
  { value: 45, label: 'Valparaíso' },
  { value: 137, label: 'Vichuquén' },
  { value: 231, label: 'Victoria' },
  { value: 35, label: 'Vicuña' },
  { value: 218, label: 'Vilcún' },
  { value: 144, label: 'Villa Alegre' },
  { value: 82, label: 'Villa Alemana' },
  { value: 219, label: 'Villarrica' },
  { value: 51, label: 'Viña del Mar' },
  { value: 326, label: 'Vitacura' },
  { value: 145, label: 'Yerbas Buenas' },
  { value: 198, label: 'Yumbel' },
  { value: 161, label: 'Yungay' },
  { value: 61, label: 'Zapallar' },
];
